In [9]:
import pandas as pd
sales = pd.read_csv("Data/sales.csv",index_col='State')
sales

,Total Expenses,Product,Sales,Market Size,Profit,Market,Marketing,Product Type,Inventory,Type
State,,,,,,,,,,
California,63.0,Amaretto,109.0,Major Market,-131.0,West,40,Coffee,2947.0,Regular
California,55.0,Green Tea,201.0,Major Market,88.0,West,24,Tea,659.0,Regular
California,143.0,Caffe Mocha,289.0,Major Market,25.0,West,109,Espresso,788.0,Regular
California,113.0,Decaf Espresso,576.0,Major Market,216.0,West,81,Espresso,1744.0,Decaf
California,37.0,Chamomile,247.0,Major Market,148.0,West,26,Herbal Tea,809.0,Decaf
...,...,...,...,...,...,...,...,...,...,...
Wisconsin,34.0,Darjeeling,90.0,Small Market,20.0,Central,11,Tea,458.0,Regular
Wisconsin,36.0,Darjeeling,113.0,Small Market,31.0,Central,14,Tea,454.0,Regular
Wisconsin,86.0,Earl Grey,150.0,Small Market,1.0,Central,57,Tea,506.0,Regular
Wisconsin,79.0,Earl Grey,131.0,Small Market,-3.0,Central,49,Tea,627.0,Regular
Wisconsin,87.0,Earl Grey,165.0,Small Market,4.0,Central,58,Tea,513.0,Regular

In [10]:
sales.Market == 'West'

State
California     True
California     True
California     True
California     True
California     True
              ...
Wisconsin     False
Wisconsin     False
Wisconsin     False
Wisconsin     False
Wisconsin     False
Name: Market, Length: 4241, dtype: bool

In [13]:
sales.loc[sales.Market == 'West']

,Total Expenses,Product,Sales,Market Size,Profit,Market,Marketing,Product Type,Inventory,Type
State,,,,,,,,,,
California,63.0,Amaretto,109.0,Major Market,-131.0,West,40,Coffee,2947.0,Regular
California,55.0,Green Tea,201.0,Major Market,88.0,West,24,Tea,659.0,Regular
California,143.0,Caffe Mocha,289.0,Major Market,25.0,West,109,Espresso,788.0,Regular
California,113.0,Decaf Espresso,576.0,Major Market,216.0,West,81,Espresso,1744.0,Decaf
California,37.0,Chamomile,247.0,Major Market,148.0,West,26,Herbal Tea,809.0,Decaf
...,...,...,...,...,...,...,...,...,...,...
Washington,35.0,Earl Grey,106.0,Small Market,28.0,West,13,Tea,466.0,Regular
Washington,32.0,Earl Grey,89.0,Small Market,28.0,West,11,Tea,462.0,Regular
Washington,36.0,Earl Grey,120.0,Small Market,46.0,West,14,Tea,454.0,Regular
Washington,36.0,Earl Grey,120.0,Small Market,46.0,West,14,Tea,449.0,Regular
Washington,26.0,Caffe Latte,109.0,Small Market,47.0,West,15,Espresso,593.0,Regular

# combining filters

In [15]:
sales.loc[(sales.Market == 'West') & (sales.Sales > 200)]

,Total Expenses,Product,Sales,Market Size,Profit,Market,Marketing,Product Type,Inventory,Type
State,,,,,,,,,,
California,55.0,Green Tea,201.0,Major Market,88.0,West,24,Tea,659.0,Regular
California,143.0,Caffe Mocha,289.0,Major Market,25.0,West,109,Espresso,788.0,Regular
California,113.0,Decaf Espresso,576.0,Major Market,216.0,West,81,Espresso,1744.0,Decaf
California,37.0,Chamomile,247.0,Major Market,148.0,West,26,Herbal Tea,809.0,Decaf
California,99.0,Lemon,582.0,Major Market,291.0,West,77,Herbal Tea,1268.0,Decaf
...,...,...,...,...,...,...,...,...,...,...
Washington,114.0,Decaf Irish Cream,239.0,Small Market,24.0,West,85,Coffee,694.0,Decaf
Washington,69.0,Chamomile,289.0,Small Market,105.0,West,37,Herbal Tea,1166.0,Decaf
Washington,75.0,Chamomile,347.0,Small Market,179.0,West,40,Herbal Tea,961.0,Decaf
Washington,62.0,Chamomile,273.0,Small Market,135.0,West,36,Herbal Tea,1020.0,Decaf
Washington,64.0,Chamomile,275.0,Small Market,135.0,West,33,Herbal Tea,1130.0,Decaf

In [16]:
sales.loc[(sales.Market == 'West') | (sales.Profit > 100)]

,Total Expenses,Product,Sales,Market Size,Profit,Market,Marketing,Product Type,Inventory,Type
State,,,,,,,,,,
California,63.0,Amaretto,109.0,Major Market,-131.0,West,40,Coffee,2947.0,Regular
California,55.0,Green Tea,201.0,Major Market,88.0,West,24,Tea,659.0,Regular
California,143.0,Caffe Mocha,289.0,Major Market,25.0,West,109,Espresso,788.0,Regular
California,113.0,Decaf Espresso,576.0,Major Market,216.0,West,81,Espresso,1744.0,Decaf
California,37.0,Chamomile,247.0,Major Market,148.0,West,26,Herbal Tea,809.0,Decaf
...,...,...,...,...,...,...,...,...,...,...
Washington,36.0,Earl Grey,120.0,Small Market,46.0,West,14,Tea,454.0,Regular
Washington,36.0,Earl Grey,120.0,Small Market,46.0,West,14,Tea,449.0,Regular
Washington,26.0,Caffe Latte,109.0,Small Market,47.0,West,15,Espresso,593.0,Regular
Wisconsin,55.0,Decaf Irish Cream,229.0,Small Market,101.0,Central,32,Coffee,565.0,Decaf
Wisconsin,45.0,Chamomile,201.0,Small Market,109.0,Central,20,Herbal Tea,400.0,Decaf

In [18]:
sales.loc[sales.Product.isin(['Amaretto'])]

,Total Expenses,Product,Sales,Market Size,Profit,Market,Marketing,Product Type,Inventory,Type
State,,,,,,,,,,
California,63.0,Amaretto,109.0,Major Market,-131.0,West,40,Coffee,2947.0,Regular
California,72.0,Amaretto,87.0,Major Market,-139.0,West,49,Coffee,2105.0,Regular
California,63.0,Amaretto,117.0,Major Market,-113.0,West,39,Coffee,964.0,Regular
California,59.0,Amaretto,116.0,Major Market,-56.0,West,36,Coffee,2758.0,Regular
California,55.0,Amaretto,141.0,Major Market,-40.0,West,33,Coffee,685.0,Regular
...,...,...,...,...,...,...,...,...,...,...
Wisconsin,54.0,Amaretto,135.0,Small Market,24.0,Central,21,Coffee,313.0,Regular
Wisconsin,51.0,Amaretto,132.0,Small Market,26.0,Central,22,Coffee,377.0,Regular
Wisconsin,54.0,Amaretto,127.0,Small Market,16.0,Central,21,Coffee,313.0,Regular
Wisconsin,56.0,Amaretto,133.0,Small Market,18.0,Central,22,Coffee,403.0,Regular
Wisconsin,58.0,Amaretto,155.0,Small Market,33.0,Central,24,Coffee,403.0,Regular

In [19]:
sales

,Total Expenses,Product,Sales,Market Size,Profit,Market,Marketing,Product Type,Inventory,Type
State,,,,,,,,,,
California,63.0,Amaretto,109.0,Major Market,-131.0,West,40,Coffee,2947.0,Regular
California,55.0,Green Tea,201.0,Major Market,88.0,West,24,Tea,659.0,Regular
California,143.0,Caffe Mocha,289.0,Major Market,25.0,West,109,Espresso,788.0,Regular
California,113.0,Decaf Espresso,576.0,Major Market,216.0,West,81,Espresso,1744.0,Decaf
California,37.0,Chamomile,247.0,Major Market,148.0,West,26,Herbal Tea,809.0,Decaf
...,...,...,...,...,...,...,...,...,...,...
Wisconsin,34.0,Darjeeling,90.0,Small Market,20.0,Central,11,Tea,458.0,Regular
Wisconsin,36.0,Darjeeling,113.0,Small Market,31.0,Central,14,Tea,454.0,Regular
Wisconsin,86.0,Earl Grey,150.0,Small Market,1.0,Central,57,Tea,506.0,Regular
Wisconsin,79.0,Earl Grey,131.0,Small Market,-3.0,Central,49,Tea,627.0,Regular
Wisconsin,87.0,Earl Grey,165.0,Small Market,4.0,Central,58,Tea,513.0,Regular

In [26]:
sales.loc[sales.Type.notnull()]

,Total Expenses,Product,Sales,Market Size,Profit,Market,Marketing,Product Type,Inventory,Type
State,,,,,,,,,,
California,63.0,Amaretto,109.0,Major Market,-131.0,West,40,Coffee,2947.0,Regular
California,55.0,Green Tea,201.0,Major Market,88.0,West,24,Tea,659.0,Regular
California,143.0,Caffe Mocha,289.0,Major Market,25.0,West,109,Espresso,788.0,Regular
California,113.0,Decaf Espresso,576.0,Major Market,216.0,West,81,Espresso,1744.0,Decaf
California,37.0,Chamomile,247.0,Major Market,148.0,West,26,Herbal Tea,809.0,Decaf
...,...,...,...,...,...,...,...,...,...,...
Wisconsin,34.0,Darjeeling,90.0,Small Market,20.0,Central,11,Tea,458.0,Regular
Wisconsin,36.0,Darjeeling,113.0,Small Market,31.0,Central,14,Tea,454.0,Regular
Wisconsin,86.0,Earl Grey,150.0,Small Market,1.0,Central,57,Tea,506.0,Regular
Wisconsin,79.0,Earl Grey,131.0,Small Market,-3.0,Central,49,Tea,627.0,Regular
Wisconsin,87.0,Earl Grey,165.0,Small Market,4.0,Central,58,Tea,513.0,Regular

In [32]:
sales['Sales'] = 'Test'
sales

,Total Expenses,Product,Sales,Market Size,Profit,Market,Marketing,Product Type,Inventory,Type
State,,,,,,,,,,
California,63.0,Amaretto,Test,Major Market,-131.0,West,40,Coffee,2947.0,Regular
California,55.0,Green Tea,Test,Major Market,88.0,West,24,Tea,659.0,Regular
California,143.0,Caffe Mocha,Test,Major Market,25.0,West,109,Espresso,788.0,Regular
California,113.0,Decaf Espresso,Test,Major Market,216.0,West,81,Espresso,1744.0,Decaf
California,37.0,Chamomile,Test,Major Market,148.0,West,26,Herbal Tea,809.0,Decaf
...,...,...,...,...,...,...,...,...,...,...
Wisconsin,34.0,Darjeeling,Test,Small Market,20.0,Central,11,Tea,458.0,Regular
Wisconsin,36.0,Darjeeling,Test,Small Market,31.0,Central,14,Tea,454.0,Regular
Wisconsin,86.0,Earl Grey,Test,Small Market,1.0,Central,57,Tea,506.0,Regular
Wisconsin,79.0,Earl Grey,Test,Small Market,-3.0,Central,49,Tea,627.0,Regular
Wisconsin,87.0,Earl Grey,Test,Small Market,4.0,Central,58,Tea,513.0,Regular

# select multiple as array

In [34]:
sales.iloc[[1,2,3,4]]

,Total Expenses,Product,Sales,Market Size,Profit,Market,Marketing,Product Type,Inventory,Type
State,,,,,,,,,,
California,55.0,Green Tea,Test,Major Market,88.0,West,24,Tea,659.0,Regular
California,143.0,Caffe Mocha,Test,Major Market,25.0,West,109,Espresso,788.0,Regular
California,113.0,Decaf Espresso,Test,Major Market,216.0,West,81,Espresso,1744.0,Decaf
California,37.0,Chamomile,Test,Major Market,148.0,West,26,Herbal Tea,809.0,Decaf

In [47]:
cols = ['Sales', 'Market Size']
indices = [0, 1, 10, 100]
#df = sales.loc[indices, cols] did not work cus indexes are not 0,1,10,100